name: Daily Commit Automation

on:
  schedule:
    # Runs every day at 06:30 UTC (adjust hour/minute as you like, but use exact values)
    - cron: "30 6 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add commit step (25f1000165@ds.study.iitm.ac.in)
        run: |
          echo "Automated update on $(date -u)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily update [$(date -u)]" || echo "No changes to commit"
          git push
